### ISSUE TITLE
Import Failed in Zabbix

### ISSUE THREAD

**Issue by stevefxp1** [kko/synology-diskstation-zabbix-snmpv3#5]
Its telling me the following: Cannot import template "Template Synology DiskStation", linked template "Template Module ICMP Ping" does not exist.

I was able to fix this by editing the XML and changing your reference to the name to ICMP Ping.
[zbx_export_SynoDiskStation_3.1.zip](https://github.com/kko/synology-diskstation-zabbix-snmpv3/files/5748836/zbx_export_SynoDiskStation_3.1.zip)

**Comment by kko** [comment]
Thanks, I fixed it.
